# This file was generated by GoReleaser. DO NOT EDIT.
cask "dirtygit" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "0d44beb3d15a8fc0c0e0a3e28ce8e025ceafb0c0933481a2cffbea6812432a8a"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5432bbc597925a629a7066d0c6620182c0024590a4ac2792eef768b6a8572ca1"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0e43ef314a17518a519e7545c5278f224a7d85aca10896399e97b7959ba6b41"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "43f45d5e21c006e387b3255f245aca3c9d120365df214102c25249a2965cc881"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dirtygit"
  desc "Finds git repos in need of commitment"
  homepage "https://github.com/boyvinall/dirtygit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dirtygit"

  # No zap stanza required

end
