# This file was generated by GoReleaser. DO NOT EDIT.
cask "dirtygit" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "d61e3692450fcd19753d108c01d6cdd00045818fcd8bf9b250f56061293a4d29"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "60852a64176f7af788c278c94fcf70c3023fa64d8f3eacd336a6ec42a72cc0f9"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c1c4dc2984bfdbd77c6ff65afe6db1e14eb50d9f462386416f111281649c1cf4"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8156e274bd3c7f3a8084c70b4ff4c51ee18ad009d184effb5b0f80bf2682a028"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dirtygit"
  desc "Finds git repos in need of commitment"
  homepage "https://github.com/boyvinall/dirtygit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dirtygit"

  # No zap stanza required

end
