# This file was generated by GoReleaser. DO NOT EDIT.
cask "dirtygit" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "afe8de6e965bd0957242ce49f5f87a4ac4655ed59a0078d3e3289e2fc063af7e"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "869510ab109875b4291513b1d61eb5f6fb8a18e22a601938848f2b7f4e27937f"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe04e788c1550de93a2cc68130a254ec960271f5d97eb8eec0cd578f1bac8147"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "011753a5882fc1ea31af842ab9207dd5b3b949e442fceeb55678007fb05cf3fe"
      url "https://github.com/boyvinall/dirtygit/releases/download/v#{version}/dirtygit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dirtygit"
  desc "Finds git repos in need of commitment"
  homepage "https://github.com/boyvinall/dirtygit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dirtygit"

  # No zap stanza required

end
